// Pixel art data for each AI provider creature.
// Each creature: { pal: {char: hexColor}, px: [rowString, ...] }
// '_' or ' ' = transparent. Grid is variable width x 20 rows.

export const CREATURES = {

  // Claude → Wise Owl
  owl: {
    color: '#D97757',
    pal: { C:'#D97757', c:'#9E4E2A', W:'#FAFAFA', K:'#1A0805', b:'#E8A882' },
    px: [
      '___CC______CC___',
      '__CcCC____CCcC__',
      '_CCcCCCCCCCCcCC_',
      'CCCCCcCCCCcCCCCC',
      'CcCCCCCCCCCCCCcC',
      'CcCWWCCCCCCWWCcC',
      'CcCWKKCCCCKKWCcC',
      'CcCWWCCCCCCWWCcC',
      'CcCCCCCCCCCCCCcC',
      'CCCCCCbbbbbCCCCC',
      'CCCCCCCbbbCCCCCC',
      '_CCCCcCCCCcCCCC_',
      'CcCCCCCCCCCCCCcC',
      'CcCCCCCCCCCCCCcC',
      'CcCCCCCCCCCCCCcC',
      'CcCCCCCCCCCCCCcC',
      '_CCCcCCCCCCcCCC_',
      '__CCCc_____cCCC_',
      '_CCCC_______CCCC',
      'CCCCC_______CCCCC',
    ],
  },

  // GPT-4o → Cunning Fox
  fox: {
    color: '#10A37F',
    pal: { G:'#10A37F', g:'#0A6F56', W:'#FAFAFA', K:'#011410', t:'#84E8CD' },
    px: [
      '___GG______GG___',
      '__GggG____GggG__',
      '__GggG____GggG__',
      '_GGGGGGGGGGGGGg_',
      'GGGGGGGGGGGGGGgg',
      'GgGWWGGGGGGWWgGG',
      'GgGWKKGGGGKKWgGG',
      'GgGGGGGGGGGGGgGG',
      'GGGGggGGGggGGGGG',
      'GGGGggGGGggGGGGG',
      '_GGGGGgGgGGGGG__',
      '__GGGGGGGGGGGt__',
      '_GGGGGGGGGGGttt_',
      'GGGGGGGGGGGGGttt',
      'GGGGGGGGGGGGGttt',
      '_GGGGGGGGGGGtttt',
      '__GGGGGGGGGtttt_',
      '___GGGGGGGGGttt_',
      '____GG___GG_____',
      '___GGGG_GGGG____',
    ],
  },

  // Gemini → Twin-Head Serpent
  serpent: {
    color: '#4285F4',
    pal: { B:'#4285F4', b:'#1B5FD4', W:'#FAFAFA', K:'#040D2A', s:'#A0C0FF' },
    px: [
      '_BB__________BB_',
      'BbbB__________BbbB',
      '_BssB________BssB',
      '_BWWBBBBBBBBBBWWBb',
      '_BWKKBssssssBKKWBb',
      '_BWWBBBBBBBBBBWWBb',
      '_BBBsBBBBBBBsBBBB',
      '__BBBBbbbbBBBBB__',
      '__BBBBBBBBBBBBb__',
      '___BBBBBBBBBBb___',
      '__BBBBbBbBBBBB___',
      '_BBBBBBBBBBBBBb__',
      '_BBBBBBBBBBBBBb__',
      '__BBBBBBBBBBBb___',
      '___BBBBBBBBBb____',
      '____BBBBBBBb_____',
      '____BBBBBBb______',
      '_____BBBBBb______',
      '_____BBBBb_______',
      '______BBb________',
    ],
  },

  // Groq → Speed Cheetah
  cheetah: {
    color: '#F97316',
    pal: { R:'#F97316', r:'#C04C08', W:'#FAFAFA', K:'#1E0800', S:'#FBD09A' },
    px: [
      '____________RRRR',
      '___________RrrrR',
      '___________RrRrR',
      '__________RrRWWR',
      '__________RRRWKR',
      '__________RRRrRR',
      'RRRRRRRRRRRRRRR_',
      'RrRRRRRRRRRRRrrR',
      'RrSRRRRSRRRSRrrR',
      'RRRSRRRRSRRRRrRR',
      'RRRRSRRRRSRRRrRR',
      'RRRRRRRRRRRRrRRR',
      '_RRRRRRRRRRRRrR_',
      '__RRRR__RRRR____',
      '____RrrR__RrrR__',
      '____RRRR__RRRR__',
      '_RRR________RRR_',
      '_RRRR_______RRRR',
      '__RR_________RR_',
      '________________',
    ],
  },

  // Ollama → Local Llama
  llama: {
    color: '#A855F7',
    pal: { P:'#A855F7', p:'#6D28D9', W:'#FAFAFA', K:'#180840', L:'#D8B4FE' },
    px: [
      '__PPP_____PPP___',
      '_PPpP_____PPpP__',
      '_PPpPP___PPpPP__',
      '_PPLLPPPPPLLPP__',
      '__PPPPpPpPPPPP__',
      '__PPWW_P_WWPPp__',
      '__PPWKK_KKWPPp__',
      '__PPWW_P_WWPPp__',
      '__PPPPpPpPPPPP__',
      '__PPPPPPPPPPPp__',
      '___PPPPPPPPPPp__',
      '___PPLLLLLPPPp__',
      '___PPPPPPPPPPp__',
      '__PPPPPPPPPPPPp_',
      '_PPPpPPPPPPpPPP_',
      'PPPpPPPPPPPPpPPP',
      'PPpPPPpPpPPPPpPP',
      '_PP__PPpPP__PPP_',
      '_LL__PPpPP__LLL_',
      '______PPP_______',
    ],
  },

  // OpenRouter → Hub Octopus
  octopus: {
    color: '#E11D48',
    pal: { E:'#E11D48', e:'#9B0A2B', W:'#FAFAFA', K:'#1C0210', s:'#FBBFCF' },
    px: [
      '____EEEEEEEE____',
      '__EEEeeeeeeeEE__',
      '_EEsEeeeeeeeseE_',
      'EEEsEEEEEEEEsEEE',
      'EEsEEWWEEWWEEsEE',
      'EEsEEWKKEKKWEsEE',
      'EEsEEWWEEWWEEsEE',
      'EEEsEEEEEEEEsEEE',
      '_EEEEEEeEEEEEE__',
      '__EEEEEeEEEEE___',
      'EE__EEEeEEE__EE_',
      'Ee__Eee_eEe__eE_',
      'Ee__Eee_eEe__eE_',
      'E___Eee_eEe___eE',
      '____Eee_eEe_____',
      '____Ee___eE_____',
      '____Ee___eE_____',
      '_____E___E______',
      '_____E___E______',
      '_____e___e______',
    ],
  },

  // xAI → Iron Bull
  bull: {
    color: '#71717A',
    pal: { X:'#71717A', x:'#44444C', W:'#FAFAFA', K:'#131316', h:'#ABABB4' },
    px: [
      'XX_XXXXXXXXXX_XX',
      'XxX_XXXXXXXXX_Xx',
      '_XxXXXXXXXXXXxX_',
      '__XXXXXXXXXXXXXX',
      '__XXhXXXXXXhXXXX',
      '__XhWWXXXXWWhXXX',
      '__XhWKKXXKKWhXXX',
      '__XhWWXXXXWWhXXX',
      '__XXhXXXXXXhXXXX',
      '__XXXXXxxXXXXXX_',
      '__XXXXXXXXXXXXXXX',
      'XXXXXXXXXXXXXXXXX',
      'XxXXXXXXXXXXXxXX',
      'XxXXXXXXXXXXXxXX',
      'XxXXXXXXXXXXXxXX',
      '_XXXXXXXXXXXXxX_',
      '__XXXXXXXXXXXXXX',
      '___XX______XX___',
      '___XX______XX___',
      '__XXXX____XXXX__',
    ],
  },

  // Together → Hive Bee
  bee: {
    color: '#F59E0B',
    pal: { A:'#F59E0B', a:'#B45309', W:'#FAFAFA', K:'#1E0F00', s:'#FDE68A' },
    px: [
      '__ssss___ssss___',
      '__ssss___ssss___',
      '____AAAAAAAA____',
      '___AAAAAAAAAA___',
      '__AAAAAAAAAAAAA_',
      'AAAAAAAAAAAAAAAA',
      'AaAWWAAAAAWWAaAA',
      'AaAWKKAAAKKWAaAA',
      'AaAWWAAAAAWWAaAA',
      'AaAAAAAAAAAAAAaA',
      'AaAAaaaaaaAAAAaA',
      'AaAAAAAAAAAAAAaA',
      'AaAAaaaaaaAAAAaA',
      'AaAAAAAAAAAAAAaA',
      'AaAAaaaaaaAAAAaA',
      '_AAAAAAAAAAAAA__',
      '__AAAAAAAAAAAA__',
      '___AAAAAAAAAAAA_',
      '_____AAAAAAA____',
      '_____AAAAA______',
    ],
  },

  // Custom → Glitch Robot
  robot: {
    color: '#8B5CF6',
    pal: { V:'#8B5CF6', v:'#5B21B6', W:'#FAFAFA', K:'#100820', g:'#C4B5FD' },
    px: [
      '______VV________',
      '_____VvV________',
      '____VvVVV_______',
      '____VVVVVVVVVV__',
      'VVV_VVVVVVVVVVV_',
      'V___VVVVVVVVVVVg',
      'VVV_VVKKVVKKVVgg',
      'VVV_VVKKVVKKVVgg',
      'VVV_VVKKVVKKVVg_',
      '____VVggggggVV__',
      '____VVVVVVVVVV__',
      '_VVVVVVVVVVVVVVV',
      'VvVVVVVVVVVVVvVV',
      'VvVVVgVVVVgVVvVV',
      'VvVVVgVVVVgVVvVV',
      'VvVVVVggggVVVvVV',
      '_VVVVVVVVVVVVv__',
      '__VV________VV__',
      '__VV________VV__',
      '_VVVV______VVVV_',
    ],
  },
};

// Which creature to show per provider/fighter id
export const FIGHTER_CREATURE = {
  claude:     'owl',
  gpt:        'fox',
  gemini:     'serpent',
  groq:       'cheetah',
  ollama:     'llama',
  openrouter: 'octopus',
  xai:        'bull',
  together:   'bee',
  custom:     'robot',
};

export function getCreature(fighterId) {
  return CREATURES[FIGHTER_CREATURE[fighterId] ?? 'robot'] ?? CREATURES.robot;
}
